# Generated by Django 3.1.12 on 2024-12-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterModelTable(
            name='payments',
            table='Payments',
        ),
    ]
